### ISSUE TITLE
Weird issue with Settings Panel

### ISSUE THREAD

**Issue by aepic999** [TheBobPony/BShell#2]
Clicking the System Properties link on the side gives you this:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at BShell.pane.LinkLabel17_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e) in D:\Documents\GitHub\BobKIOSK\BobKIOSK\settings\pane.vb:line 86
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
After looking in pane.vb, LinkLabel17 attempts to run Process.Start on "control.exe sysdm.cpl", which I tried in the Run dialog (Win+R) and it seems to work fine.

**Comment by TheBobPony** [comment]
Now fixed with new commit. 😉
